<a href="https://colab.research.google.com/github/Neermita18/Deep-Learning/blob/main/DL_assignment_1_Neermita.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import torchvision
from torchvision import *
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda

In [5]:
pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.10/dist-packages (0.3.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from kagglehub) (24.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kagglehub) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->kagglehub) (2024.12.14)

In [6]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("fedesoriano/stellar-classification-dataset-sdss17")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.5), please consider upgrading to the latest version (0.3.6).
Downloading from https://www.kaggle.com/api/v1/datasets/download/fedesoriano/stellar-classification-dataset-sdss17?dataset_version_number=1...

100%|██████████| 6.89M/6.89M [00:00<00:00, 26.4MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/fedesoriano/stellar-classification-dataset-sdss17/versions/1

In [7]:
df= pd.read_csv("/root/.cache/kagglehub/datasets/fedesoriano/stellar-classification-dataset-sdss17/versions/1/star_classification.csv")

In [8]:
df

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID
0,1.237661e+18,135.689107,32.494632,23.87882,22.27530,20.39501,19.16573,18.79371,3606,301,2,79,6.543777e+18,GALAXY,0.634794,5812,56354,171
1,1.237665e+18,144.826101,31.274185,24.77759,22.83188,22.58444,21.16812,21.61427,4518,301,5,119,1.176014e+19,GALAXY,0.779136,10445,58158,427
2,1.237661e+18,142.188790,35.582444,25.26307,22.66389,20.60976,19.34857,18.94827,3606,301,2,120,5.152200e+18,GALAXY,0.644195,4576,55592,299
3,1.237663e+18,338.741038,-0.402828,22.13682,23.77656,21.61162,20.50454,19.25010,4192,301,3,214,1.030107e+19,GALAXY,0.932346,9149,58039,775
4,1.237680e+18,345.282593,21.183866,19.43718,17.58028,16.49747,15.97711,15.54461,8102,301,3,137,6.891865e+18,GALAXY,0.116123,6121,56187,842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.237679e+18,39.620709,-2.594074,22.16759,22.97586,21.90404,21.30548,20.73569,7778,301,2,581,1.055431e+19,GALAXY,0.000000,9374,57749,438
99996,1.237679e+18,29.493819,19.798874,22.69118,22.38628,20.45003,19.75759,19.41526,7917,301,1,289,8.586351e+18,GALAXY,0.404895,7626,56934,866
99997,1.237668e+18,224.587407,15.700707,21.16916,19.26997,18.20428,17.69034,17.35221,5314,301,4,308,3.112008e+18,GALAXY,0.143366,2764,54535,74
99998,1.237661e+18,212.268621,46.660365,25.35039,21.63757,19.91386,19.07254,18.62482,3650,301,4,131,7.601080e+18,GALAXY,0.455040,6751,56368,470
99999,1.237661e+18,196.896053,49.464643,22.62171,21.79745,20.60115,20.00959,19.28075,3650,301,4,60,8.343152e+18,GALAXY,0.542944,7410,57104,851

In [9]:
df["class"]

0        GALAXY
1        GALAXY
2        GALAXY
3        GALAXY
4        GALAXY
          ...
99995    GALAXY
99996    GALAXY
99997    GALAXY
99998    GALAXY
99999    GALAXY
Name: class, Length: 100000, dtype: object

In [20]:
class AstroDataset(Dataset):
  def __init__(self, df, X_transform=None, y_transform=None):
    self.data = df
    self.X_transform = X_transform
    self.y_transform= y_transform
  def __len__(self):
    return self.data.shape[0]
  def __getitem__(self, idx):
    X= self.data.drop(columns=["class"])
    y= self.data["class"]
    X = X.iloc[idx]
    y = y.iloc[idx]
    if self.X_transform:
      X= self.X_transform(X)
    if self.y_transform:
      y= self.y_transform(y)
    return X,y

In [21]:
train_dataset= AstroDataset(df)

In [22]:
a,b=train_dataset[0]

In [23]:
a

obj_ID         1.237661e+18
alpha          1.356891e+02
delta          3.249463e+01
u              2.387882e+01
g              2.227530e+01
r              2.039501e+01
i              1.916573e+01
z              1.879371e+01
run_ID         3.606000e+03
rerun_ID       3.010000e+02
cam_col        2.000000e+00
field_ID       7.900000e+01
spec_obj_ID    6.543777e+18
redshift       6.347936e-01
plate          5.812000e+03
MJD            5.635400e+04
fiber_ID       1.710000e+02
Name: 0, dtype: float64

In [24]:
b

'GALAXY'